### ISSUE TITLE
Question about updating and potential bug? 

### ISSUE THREAD

**Issue by gpl872** [soid/peqod#1]
I have some questions about instructor updating? 

For https://peqod.com/course/ERMC-PS5900/2024-Fall, Call number: 16004 The instructor is no longer referenced on the Columbia's directory of classes website but is still present on peqod's instructor page. Is it possible to update it and delete it (the instructor) until a new instructor is added? 

1. What happens in cases like this where a person never instructed before, is added to the instructor page of peqod, and then removed. To ensure the integrity of peqod, when would the instructor section remove this instructor since they never taught? 
2.  How often are the datapulls performing integrity checks comparing the existing database? 
3. Are the new instructors just appended the peqod instructor page? When are they updated in cases like this? 
4. In instances where the instructor changes their name to shorten it for instance (daniel to dan) how does that update?  Please see image below, are there instances if the instructor is removed and then renamed and then added back would result in a duplication? Or does it need to be overwritten with a new instructor? 

![image](https://github.com/user-attachments/assets/4ec1d41c-243c-4647-9092-80448041f52d)

I appreciate your time. @soid

**Comment by soid** [comment]
Thanks for the report! Fixed the website update https://github.com/soid/peqod/commit/824bf31afc188391083b129ed5ba562a1bb13777 The website should be consistent with respect to the bug that you described.

2. The website database is denormalized, so it should be consistent. The [source files in another repository](https://github.com/soid/columbia-catalog-data) have some denormalized fields for convenience that might be inconsistent.
3. New instructors are appended in the source files as , but the website shows the database that should be consistent.
4. Currently it doesn't support multiple names or aliases for instructors

**Comment by soid** [comment]
Regarding 4, I will add that even we don’t track name changes automatically, if you want to propose change something you’re welcome to do so. In fact, you can just change the source files (https://github.com/soid/columbia-catalog-data) and submit a pull request. Or you can request a change by filing an issue like this one. 
Let me know if you have any other questions.
